services:
  amass-api:
    build: .
    # image: enrikenur/amass-api:latest
    container_name: amass-api
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./results:/results
